name       : akonadi-mime
version    : 18.08.1
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/akonadi-mime-18.08.1.tar.xz : af606127e9454568e9e8554942c5102d5eefe6b6a3875e1579c583e1d62cae13
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - akonadi-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - libboost-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
