name       : akonadi-mime
version    : 17.08.1
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/akonadi-mime-17.08.1.tar.xz : db3c5fe7a3b15aeb6f285ec891bf180964c849ee2bb6ffac5f45de1a7242f4aa
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic
    API of the Akonadi client libraries and the domain-specific KMime library.
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - akonadi-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - libboost-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
