name       : akonadi-mime
version    : 18.04.1
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/akonadi-mime-18.04.1.tar.xz : bc3e0c793fa700749d825ec03bda2478513c4a23ba77f47cbbde0a88725eee7a
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library.
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - akonadi-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - libboost-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
