name       : akonadi-mime
version    : 20.04.3
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/akonadi-mime-20.04.3.tar.xz : 92e9bab71f87c0de8e3437dd4779054332826fe2522c36a7c038c789b207f7ac
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - akonadi-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - kwindowsystem-devel
    - libboost-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
