name       : akonadi-mime
version    : 19.08.1
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/akonadi-mime-19.08.1.tar.xz : 0a4f4652a665229b290431adb59940890effba0804fe33a0e79a24322f90b35c
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - akonadi-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - libboost-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
