name       : akonadi-mime
version    : 21.04.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/akonadi-mime-21.04.1.tar.xz : 7e9a2a4bba6c39c0d6e24d8479199988e8726a229d6ff66853c943cc4dbe2d33
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(libxslt)
    - akonadi-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
