name       : akonadi-mime
version    : 22.04.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/akonadi-mime-22.04.0.tar.xz : 31af3ef9c9dba425081cdff3c1cb64ac6804f61bf9e83690afcb7dd651fc2867
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(libxslt)
    - akonadi-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
