name       : akonadi-mime
version    : 19.08.2
release    : 28
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/akonadi-mime-19.08.2.tar.xz : 16f8034d7990828c50a85474fe16641dfa46e22d00f49d8045d3483c61815264
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - akonadi-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - libboost-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
