name       : akonadi-mime
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/akonadi-mime-17.08.3.tar.xz : 6892e8209a87e609fb0bdcc929d8efbbd75c20fbf9a20a8c2e6a2501fde6e48c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library.
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - akonadi-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - libboost-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
