name       : akonadi-mime
version    : 22.04.2
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/akonadi-mime-22.04.2.tar.xz : 927e8429d33abdd96b5045cfcd9f0100eb6ade1fcd68f5a19e65aa5fb87c5226
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(libxslt)
    - akonadi-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
