name       : akonadi-mime
version    : 20.12.3
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/akonadi-mime-20.12.3.tar.xz : f45d97ddfed592db897cb7dd0e50183dd72b0f2bdb761168917bd4b739d7ddb6
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library
description: |
    Akonadi Mime is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KMime library. It provides jobs, models and other helpers to make working with emails through Akonadi easier.
builddeps  :
    - pkgconfig(libxslt)
    - akonadi-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
